<?php 
$locale = array(
                "assigned_user_id" => "Asignado"
                ,"created_by" => "Creado por"
                ,"date_due" => "Fecha fin"
                ,"date_entered" => "Fecha creación"
                ,"date_start" => "Fecha inicio"
                ,"description" => "Descripción"
                ,"estadonc" => "Estado"
                ,"fuentenc" => "Fuente"
                ,"files" => "Archivos"
                ,"generalidadnc" => "Generalidad"
                ,"gestion" => "Gestión"
                ,"name" => "Nombre"
                ,"nombre_del_clientenc" => "Nombre del cliente"
                ,"nonConformity" => "Quejas y reclamos"
                ,"nonConformityId" => "No."
                ,"noteId" => "No."
                ,"notes" => "Notas"
                ,"noteTypeId" => "Tipo de nota"
                ,"priority" => "Prioridad"
                ,"sedenc" => "Sede"
                ,"status" => "Estado"
                ,"taskId" => "No."
                ,"tasks" => "Tareas"
                ,"telefononc" => "Teléfono"
            );
?>